import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedCharities() {
  console.log("Seeding charity organizations...");

  const charities = [
    {
      id: "charity-save-the-children",
      name: "Save the Children",
      description: "Leading global organization for children, working in 120+ countries to give children a healthy start, learning opportunities, and protection from harm.",
      website: "https://www.savethechildren.org",
      countries: ["US", "UK", "India", "Ethiopia", "Bangladesh", "Nigeria", "Syria", "Yemen", "Somalia", "South Sudan"],
      focus: ["child welfare", "education", "disaster relief", "health", "nutrition"],
      isActive: true,
    },
    {
      id: "charity-family-promise",
      name: "Family Promise",
      description: "National nonprofit addressing family homelessness through a network of 200+ communities across the US, helping families achieve sustainable independence.",
      website: "https://familypromise.org",
      countries: ["US"],
      focus: ["family homelessness", "housing", "family support", "community development"],
      isActive: true,
    },
    {
      id: "charity-world-vision",
      name: "World Vision",
      description: "Christian humanitarian organization dedicated to working with children, families, and communities to overcome poverty and injustice in nearly 100 countries.",
      website: "https://www.worldvision.org",
      countries: ["US", "Kenya", "India", "Philippines", "Guatemala", "Honduras", "Romania", "Zambia", "Uganda", "Malawi"],
      focus: ["child sponsorship", "clean water", "education", "economic empowerment", "disaster relief"],
      isActive: true,
    },
    {
      id: "charity-unicef",
      name: "UNICEF",
      description: "United Nations agency responsible for providing humanitarian and developmental aid to children worldwide, operating in over 190 countries.",
      website: "https://www.unicef.org",
      countries: ["US", "India", "Nigeria", "Bangladesh", "Brazil", "Pakistan", "Ethiopia", "DR Congo", "Indonesia", "Mexico"],
      focus: ["child health", "nutrition", "education", "emergency relief", "water and sanitation"],
      isActive: true,
    },
    {
      id: "charity-salvation-army",
      name: "The Salvation Army",
      description: "International charitable organization providing disaster relief, family services, and community programs in 133 countries around the world.",
      website: "https://www.salvationarmyusa.org",
      countries: ["US", "UK", "Australia", "Canada", "India", "Kenya", "Brazil", "Japan", "South Korea", "Germany"],
      focus: ["family services", "disaster relief", "addiction recovery", "housing", "youth programs"],
      isActive: true,
    },
    {
      id: "charity-feeding-america",
      name: "Feeding America",
      description: "Largest hunger-relief organization in the US, operating a nationwide network of 200 food banks serving every community in America.",
      website: "https://www.feedingamerica.org",
      countries: ["US"],
      focus: ["food security", "hunger relief", "nutrition", "community support"],
      isActive: true,
    },
  ];

  for (const charity of charities) {
    await prisma.charityOrganization.upsert({
      where: { id: charity.id },
      update: charity,
      create: charity,
    });
  }
  console.log(`  Seeded ${charities.length} charity organizations`);
}

async function seedActivities() {
  console.log("Seeding activities for 5 launch cities...");

  const activities = [
    // ========== SALT LAKE CITY, UT ==========
    {
      id: "act-slc-liberty-park",
      title: "Liberty Park",
      description: "80-acre urban park with playgrounds, a pond, tennis courts, and the Tracy Aviary. Perfect for a family day out.",
      category: "PARK" as const,
      latitude: 40.7447, longitude: -111.8760,
      address: "600 E 900 S, Salt Lake City, UT 84105",
      city: "Salt Lake City", state: "UT", zipCode: "84105",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["park", "playground", "family", "aviary", "picnic"],
      rating: 4.6, reviewCount: 3200,
    },
    {
      id: "act-slc-natural-history",
      title: "Natural History Museum of Utah",
      description: "World-class museum at the Rio Tinto Center featuring Utah's geological and natural history, dinosaur exhibits, and interactive galleries.",
      category: "MUSEUM" as const,
      latitude: 40.7582, longitude: -111.8245,
      address: "301 Wakara Way, Salt Lake City, UT 84108",
      city: "Salt Lake City", state: "UT", zipCode: "84108",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 3, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["museum", "dinosaurs", "science", "kids", "education"],
      rating: 4.7, reviewCount: 5600,
    },
    {
      id: "act-slc-bonneville-shoreline",
      title: "Bonneville Shoreline Trail",
      description: "Popular multi-use trail along the ancient Lake Bonneville shoreline. Great for family hikes with stunning valley views.",
      category: "TRAIL" as const,
      latitude: 40.7608, longitude: -111.8162,
      address: "Bonneville Shoreline Trail, Salt Lake City, UT",
      city: "Salt Lake City", state: "UT",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 5, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["hiking", "trail", "views", "nature", "exercise"],
      rating: 4.5, reviewCount: 1800,
    },
    {
      id: "act-slc-hogle-zoo",
      title: "Utah's Hogle Zoo",
      description: "Home to over 800 animals from around the world. Features the Rocky Shores exhibit, elephant encounter, and seasonal events.",
      category: "ENTERTAINMENT" as const,
      latitude: 40.7500, longitude: -111.8145,
      address: "2600 Sunnyside Ave, Salt Lake City, UT 84108",
      city: "Salt Lake City", state: "UT", zipCode: "84108",
      cost: "MODERATE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["zoo", "animals", "kids", "family", "outdoor"],
      rating: 4.4, reviewCount: 4200,
    },
    {
      id: "act-slc-snowbird",
      title: "Snowbird Ski Resort",
      description: "Premier ski resort in Little Cottonwood Canyon. Summer activities include the alpine slide, mountain coaster, and scenic tram rides.",
      category: "OUTDOOR" as const,
      latitude: 40.5830, longitude: -111.6538,
      address: "9385 S Snowbird Center Dr, Snowbird, UT 84092",
      city: "Salt Lake City", state: "UT", zipCode: "84092",
      cost: "EXPENSIVE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 4, ageMax: 99,
      seasonality: ["winter", "summer"],
      tags: ["skiing", "snowboarding", "alpine slide", "mountains", "adventure"],
      rating: 4.6, reviewCount: 7800,
    },
    {
      id: "act-slc-discovery-gateway",
      title: "Discovery Gateway Children's Museum",
      description: "Interactive children's museum in downtown SLC with hands-on exhibits focused on learning through play.",
      category: "MUSEUM" as const,
      latitude: 40.7677, longitude: -111.9011,
      address: "444 W 100 S, Salt Lake City, UT 84101",
      city: "Salt Lake City", state: "UT", zipCode: "84101",
      cost: "BUDGET" as const, isIndoor: true, isOutdoor: false,
      ageMin: 1, ageMax: 12,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["children", "museum", "interactive", "play", "education"],
      rating: 4.3, reviewCount: 2100,
    },
    {
      id: "act-slc-red-butte-garden",
      title: "Red Butte Garden",
      description: "Botanical garden and arboretum with beautiful trails, themed gardens, and a popular summer concert series.",
      category: "PARK" as const,
      latitude: 40.7660, longitude: -111.8258,
      address: "300 Wakara Way, Salt Lake City, UT 84108",
      city: "Salt Lake City", state: "UT", zipCode: "84108",
      cost: "BUDGET" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["garden", "botanical", "concerts", "nature", "walking"],
      rating: 4.7, reviewCount: 3400,
    },
    {
      id: "act-slc-the-living-room",
      title: "Living Room Trailhead Hike",
      description: "Popular family-friendly hike leading to natural rock 'chairs' with panoramic views of the Salt Lake Valley.",
      category: "TRAIL" as const,
      latitude: 40.7630, longitude: -111.8130,
      address: "Living Room Trailhead, Salt Lake City, UT",
      city: "Salt Lake City", state: "UT",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 6, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["hiking", "views", "family", "nature", "exercise"],
      rating: 4.5, reviewCount: 1500,
    },
    // ========== DALLAS-FORT WORTH, TX ==========
    {
      id: "act-dfw-perot-museum",
      title: "Perot Museum of Nature and Science",
      description: "World-class science museum with 11 permanent exhibit halls, including dinosaurs, space, gems, and an engineering design lab.",
      category: "MUSEUM" as const,
      latitude: 32.7868, longitude: -96.8066,
      address: "2201 N Field St, Dallas, TX 75201",
      city: "Dallas", state: "TX", zipCode: "75201",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 2, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["museum", "science", "dinosaurs", "kids", "education", "interactive"],
      rating: 4.6, reviewCount: 8900,
    },
    {
      id: "act-dfw-klyde-warren",
      title: "Klyde Warren Park",
      description: "5.2-acre urban park built over a freeway, featuring food trucks, free fitness classes, a children's park, and live music.",
      category: "PARK" as const,
      latitude: 32.7893, longitude: -96.8016,
      address: "2012 Woodall Rodgers Fwy, Dallas, TX 75201",
      city: "Dallas", state: "TX", zipCode: "75201",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["park", "food trucks", "playground", "free", "downtown"],
      rating: 4.7, reviewCount: 12000,
    },
    {
      id: "act-dfw-fort-worth-stockyards",
      title: "Fort Worth Stockyards",
      description: "Historic district with daily cattle drives, rodeos, western shops, and family-friendly restaurants. A Texas must-see.",
      category: "ENTERTAINMENT" as const,
      latitude: 32.7873, longitude: -97.3480,
      address: "131 E Exchange Ave, Fort Worth, TX 76164",
      city: "Fort Worth", state: "TX", zipCode: "76164",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["western", "cattle", "rodeo", "history", "shopping", "family"],
      rating: 4.5, reviewCount: 15000,
    },
    {
      id: "act-dfw-dallas-arboretum",
      title: "Dallas Arboretum and Botanical Garden",
      description: "66-acre garden on White Rock Lake with seasonal flower displays, a children's adventure garden, and concerts.",
      category: "PARK" as const,
      latitude: 32.8231, longitude: -96.7167,
      address: "8525 Garland Rd, Dallas, TX 75218",
      city: "Dallas", state: "TX", zipCode: "75218",
      cost: "BUDGET" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["garden", "botanical", "flowers", "kids", "nature"],
      rating: 4.7, reviewCount: 9500,
    },
    {
      id: "act-dfw-legoland",
      title: "LEGOLAND Discovery Center",
      description: "Indoor LEGO-themed attraction with rides, a 4D cinema, building workshops, and MINILAND featuring Dallas landmarks.",
      category: "ENTERTAINMENT" as const,
      latitude: 32.8329, longitude: -96.8472,
      address: "3000 Grapevine Mills Pkwy, Grapevine, TX 76051",
      city: "Dallas", state: "TX", zipCode: "76051",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 3, ageMax: 12,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["lego", "kids", "rides", "indoor", "building"],
      rating: 4.2, reviewCount: 4500,
    },
    {
      id: "act-dfw-top-golf",
      title: "Topgolf Dallas",
      description: "High-tech driving range with climate-controlled hitting bays, games for all ages, dining, and a rooftop terrace.",
      category: "SPORTS" as const,
      latitude: 32.8150, longitude: -96.8716,
      address: "8787 Park Ln, Dallas, TX 75231",
      city: "Dallas", state: "TX", zipCode: "75231",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: true,
      ageMin: 6, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["golf", "entertainment", "food", "family", "games"],
      rating: 4.3, reviewCount: 6800,
    },
    {
      id: "act-dfw-white-rock-lake",
      title: "White Rock Lake Park",
      description: "1,015-acre park with 9-mile hike/bike trail, kayaking, sailing, picnic areas, and scenic views of downtown Dallas.",
      category: "OUTDOOR" as const,
      latitude: 32.8367, longitude: -96.7225,
      address: "8300 E Lawther Dr, Dallas, TX 75218",
      city: "Dallas", state: "TX", zipCode: "75218",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["lake", "biking", "kayaking", "hiking", "nature", "picnic"],
      rating: 4.6, reviewCount: 5200,
    },
    {
      id: "act-dfw-medieval-times",
      title: "Medieval Times Dinner & Tournament",
      description: "Exciting dinner show featuring jousting knights, sword fights, and a four-course feast — all served without utensils!",
      category: "ENTERTAINMENT" as const,
      latitude: 32.8402, longitude: -96.9722,
      address: "2021 N Stemmons Fwy, Dallas, TX 75207",
      city: "Dallas", state: "TX", zipCode: "75207",
      cost: "EXPENSIVE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 3, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["dinner show", "knights", "family", "entertainment", "medieval"],
      rating: 4.4, reviewCount: 7200,
    },
    // ========== PHOENIX, AZ ==========
    {
      id: "act-phx-desert-botanical",
      title: "Desert Botanical Garden",
      description: "55-acre garden showcasing desert plants from around the world, with seasonal exhibits, butterfly pavilion, and flashlight tours.",
      category: "PARK" as const,
      latitude: 33.4618, longitude: -111.9446,
      address: "1201 N Galvin Pkwy, Phoenix, AZ 85008",
      city: "Phoenix", state: "AZ", zipCode: "85008",
      cost: "MODERATE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["fall", "winter", "spring"],
      tags: ["garden", "desert", "plants", "nature", "walking"],
      rating: 4.7, reviewCount: 11000,
    },
    {
      id: "act-phx-camelback",
      title: "Camelback Mountain",
      description: "Iconic Phoenix landmark with two challenging but rewarding trails offering panoramic views of the Valley of the Sun.",
      category: "TRAIL" as const,
      latitude: 33.5133, longitude: -111.9710,
      address: "4925 E McDonald Dr, Phoenix, AZ 85018",
      city: "Phoenix", state: "AZ", zipCode: "85018",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 10, ageMax: 70,
      seasonality: ["fall", "winter", "spring"],
      tags: ["hiking", "mountain", "views", "exercise", "challenging"],
      rating: 4.6, reviewCount: 14000,
    },
    {
      id: "act-phx-childrens-museum",
      title: "Children's Museum of Phoenix",
      description: "Interactive museum with 300+ hands-on exhibits spread across three floors, focused on learning through play for kids 0-10.",
      category: "MUSEUM" as const,
      latitude: 33.4504, longitude: -112.0663,
      address: "215 N 7th St, Phoenix, AZ 85034",
      city: "Phoenix", state: "AZ", zipCode: "85034",
      cost: "BUDGET" as const, isIndoor: true, isOutdoor: false,
      ageMin: 0, ageMax: 10,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["children", "museum", "interactive", "play", "indoor"],
      rating: 4.5, reviewCount: 4800,
    },
    {
      id: "act-phx-odysea-aquarium",
      title: "OdySea Aquarium",
      description: "Arizona's largest aquarium with 2 million gallons of water, penguin encounters, shark voyages, and a sea lion splash.",
      category: "ENTERTAINMENT" as const,
      latitude: 33.5533, longitude: -111.8765,
      address: "9500 E Via de Ventura, Scottsdale, AZ 85256",
      city: "Phoenix", state: "AZ", zipCode: "85256",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["aquarium", "marine life", "sharks", "penguins", "kids"],
      rating: 4.4, reviewCount: 7600,
    },
    {
      id: "act-phx-papago-park",
      title: "Papago Park",
      description: "1,200-acre park with easy hiking trails, the iconic Hole-in-the-Rock formation, fishing lagoons, and picnic areas.",
      category: "PARK" as const,
      latitude: 33.4539, longitude: -111.9486,
      address: "625 N Galvin Pkwy, Phoenix, AZ 85008",
      city: "Phoenix", state: "AZ", zipCode: "85008",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["fall", "winter", "spring"],
      tags: ["park", "hiking", "fishing", "picnic", "scenic"],
      rating: 4.5, reviewCount: 6200,
    },
    {
      id: "act-phx-splash-pads",
      title: "Tempe Beach Park Splash Pad",
      description: "Free splash pad along Tempe Town Lake, perfect for cooling off in the Arizona heat. Adjacent to playground and walking paths.",
      category: "PLAYGROUND" as const,
      latitude: 33.4311, longitude: -111.9412,
      address: "80 W Rio Salado Pkwy, Tempe, AZ 85281",
      city: "Phoenix", state: "AZ", zipCode: "85281",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 1, ageMax: 12,
      seasonality: ["spring", "summer"],
      tags: ["splash pad", "water play", "kids", "free", "cooling off"],
      rating: 4.3, reviewCount: 1800,
    },
    {
      id: "act-phx-musical-instrument",
      title: "Musical Instrument Museum",
      description: "The world's only global musical instrument museum with 7,000+ instruments from 200 countries, plus interactive galleries.",
      category: "MUSEUM" as const,
      latitude: 33.6668, longitude: -111.9783,
      address: "4725 E Mayo Blvd, Phoenix, AZ 85050",
      city: "Phoenix", state: "AZ", zipCode: "85050",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 5, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["museum", "music", "instruments", "interactive", "culture"],
      rating: 4.8, reviewCount: 9200,
    },
    {
      id: "act-phx-butterfly-wonderland",
      title: "Butterfly Wonderland",
      description: "Largest butterfly conservatory in America with thousands of butterflies, a 3D theater, and interactive exhibits.",
      category: "ENTERTAINMENT" as const,
      latitude: 33.5528, longitude: -111.8760,
      address: "9500 E Via de Ventura Suite 101, Scottsdale, AZ 85256",
      city: "Phoenix", state: "AZ", zipCode: "85256",
      cost: "BUDGET" as const, isIndoor: true, isOutdoor: false,
      ageMin: 2, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["butterflies", "nature", "kids", "indoor", "conservatory"],
      rating: 4.4, reviewCount: 5100,
    },
    // ========== NASHVILLE, TN ==========
    {
      id: "act-nash-centennial-park",
      title: "Centennial Park & The Parthenon",
      description: "132-acre park featuring a full-scale replica of the Greek Parthenon, walking trails, a lake, and an arts center.",
      category: "PARK" as const,
      latitude: 36.1496, longitude: -86.8130,
      address: "2500 West End Ave, Nashville, TN 37203",
      city: "Nashville", state: "TN", zipCode: "37203",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["park", "parthenon", "history", "walking", "family"],
      rating: 4.7, reviewCount: 9800,
    },
    {
      id: "act-nash-adventure-science",
      title: "Adventure Science Center",
      description: "Hands-on science museum with 175+ interactive exhibits, a planetarium, and a 75-foot climbing tower.",
      category: "MUSEUM" as const,
      latitude: 36.1383, longitude: -86.7773,
      address: "800 Fort Negley Blvd, Nashville, TN 37203",
      city: "Nashville", state: "TN", zipCode: "37203",
      cost: "BUDGET" as const, isIndoor: true, isOutdoor: false,
      ageMin: 2, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["science", "museum", "interactive", "planetarium", "kids"],
      rating: 4.5, reviewCount: 5400,
    },
    {
      id: "act-nash-grand-ole-opry",
      title: "Grand Ole Opry",
      description: "Legendary country music venue hosting live shows since 1925. Family-friendly performances featuring top country artists.",
      category: "ENTERTAINMENT" as const,
      latitude: 36.2053, longitude: -86.6916,
      address: "2804 Opryland Dr, Nashville, TN 37214",
      city: "Nashville", state: "TN", zipCode: "37214",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 5, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["music", "country", "live show", "entertainment", "iconic"],
      rating: 4.7, reviewCount: 18000,
    },
    {
      id: "act-nash-nashville-zoo",
      title: "Nashville Zoo at Grassmere",
      description: "200-acre zoo with 6,000+ animals, a jungle gym, train rides, and seasonal events like Zoo Lights.",
      category: "ENTERTAINMENT" as const,
      latitude: 36.1167, longitude: -86.7406,
      address: "3777 Nolensville Pike, Nashville, TN 37211",
      city: "Nashville", state: "TN", zipCode: "37211",
      cost: "MODERATE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["zoo", "animals", "kids", "family", "train ride"],
      rating: 4.6, reviewCount: 8200,
    },
    {
      id: "act-nash-percy-warner",
      title: "Percy Warner Park",
      description: "2,684-acre park with scenic drives, hiking trails, equestrian trails, and beautiful stone steps. One of the largest city parks in the US.",
      category: "TRAIL" as const,
      latitude: 36.0684, longitude: -86.8833,
      address: "7311 TN-100, Nashville, TN 37221",
      city: "Nashville", state: "TN", zipCode: "37221",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 3, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["hiking", "nature", "trails", "scenic", "large park"],
      rating: 4.7, reviewCount: 4100,
    },
    {
      id: "act-nash-hattie-bs",
      title: "Hattie B's Hot Chicken",
      description: "Nashville's famous hot chicken restaurant. Family-friendly atmosphere with heat levels from Southern (mild) to Shut the Cluck Up.",
      category: "RESTAURANT" as const,
      latitude: 36.1528, longitude: -86.8028,
      address: "112 19th Ave S, Nashville, TN 37203",
      city: "Nashville", state: "TN", zipCode: "37203",
      cost: "BUDGET" as const, isIndoor: true, isOutdoor: false,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["restaurant", "hot chicken", "nashville", "dining", "family"],
      rating: 4.4, reviewCount: 12000,
    },
    {
      id: "act-nash-shelby-bottoms",
      title: "Shelby Bottoms Greenway",
      description: "810-acre nature park along the Cumberland River with paved greenway trails, a nature center, and wildlife viewing.",
      category: "OUTDOOR" as const,
      latitude: 36.1808, longitude: -86.7284,
      address: "1900 Davidson St, Nashville, TN 37206",
      city: "Nashville", state: "TN", zipCode: "37206",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["greenway", "biking", "nature", "walking", "river"],
      rating: 4.6, reviewCount: 3800,
    },
    {
      id: "act-nash-franklins",
      title: "Downtown Franklin",
      description: "Charming historic town 20 min from Nashville with boutique shops, restaurants, Civil War sites, and seasonal festivals.",
      category: "SHOPPING" as const,
      latitude: 35.9251, longitude: -86.8689,
      address: "Main Street, Franklin, TN 37064",
      city: "Nashville", state: "TN", zipCode: "37064",
      cost: "FREE" as const, isIndoor: true, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["shopping", "historic", "restaurants", "charming", "walking"],
      rating: 4.6, reviewCount: 5600,
    },
    // ========== CHARLOTTE, NC ==========
    {
      id: "act-clt-discovery-place",
      title: "Discovery Place Science",
      description: "Premier science museum with interactive exhibits, an IMAX theater, aquarium, and a World Alive tropical rainforest.",
      category: "MUSEUM" as const,
      latitude: 35.2294, longitude: -80.8424,
      address: "301 N Tryon St, Charlotte, NC 28202",
      city: "Charlotte", state: "NC", zipCode: "28202",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 2, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["science", "museum", "IMAX", "aquarium", "interactive"],
      rating: 4.5, reviewCount: 6200,
    },
    {
      id: "act-clt-freedom-park",
      title: "Freedom Park",
      description: "98-acre park with a 7-acre lake, playgrounds, tennis courts, baseball fields, and paved walking trails.",
      category: "PARK" as const,
      latitude: 35.1933, longitude: -80.8293,
      address: "1900 East Blvd, Charlotte, NC 28203",
      city: "Charlotte", state: "NC", zipCode: "28203",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["park", "lake", "playground", "walking", "family"],
      rating: 4.6, reviewCount: 3400,
    },
    {
      id: "act-clt-carowinds",
      title: "Carowinds",
      description: "300-acre amusement park straddling the NC/SC border with roller coasters, a waterpark, and Camp Snoopy for kids.",
      category: "ENTERTAINMENT" as const,
      latitude: 35.1025, longitude: -80.9436,
      address: "14523 Carowinds Blvd, Charlotte, NC 28273",
      city: "Charlotte", state: "NC", zipCode: "28273",
      cost: "EXPENSIVE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 3, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["amusement park", "roller coasters", "waterpark", "kids", "thrill rides"],
      rating: 4.3, reviewCount: 15000,
    },
    {
      id: "act-clt-us-whitewater",
      title: "U.S. National Whitewater Center",
      description: "World's largest artificial whitewater river with rafting, kayaking, zip lines, rock climbing, mountain biking, and more.",
      category: "OUTDOOR" as const,
      latitude: 35.2721, longitude: -80.9559,
      address: "5000 Whitewater Center Pkwy, Charlotte, NC 28214",
      city: "Charlotte", state: "NC", zipCode: "28214",
      cost: "MODERATE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 6, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["whitewater", "adventure", "rafting", "zip line", "climbing", "biking"],
      rating: 4.6, reviewCount: 8400,
    },
    {
      id: "act-clt-imaginon",
      title: "ImaginOn: The Joe & Joan Martin Center",
      description: "Library and theater for young people with interactive story labs, teen tech center, and live performances for families.",
      category: "ARTS" as const,
      latitude: 35.2255, longitude: -80.8390,
      address: "300 E 7th St, Charlotte, NC 28202",
      city: "Charlotte", state: "NC", zipCode: "28202",
      cost: "FREE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 0, ageMax: 18,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["library", "theater", "kids", "free", "stories", "arts"],
      rating: 4.5, reviewCount: 2200,
    },
    {
      id: "act-clt-nascar-hall",
      title: "NASCAR Hall of Fame",
      description: "Interactive entertainment complex honoring NASCAR's history. Features racing simulators, a Glory Road banked track display, and artifacts.",
      category: "MUSEUM" as const,
      latitude: 35.2219, longitude: -80.8455,
      address: "400 E Martin Luther King Jr Blvd, Charlotte, NC 28202",
      city: "Charlotte", state: "NC", zipCode: "28202",
      cost: "MODERATE" as const, isIndoor: true, isOutdoor: false,
      ageMin: 5, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["NASCAR", "racing", "museum", "simulators", "interactive"],
      rating: 4.4, reviewCount: 5600,
    },
    {
      id: "act-clt-reedy-creek",
      title: "Reedy Creek Nature Preserve",
      description: "927-acre nature preserve with 10 miles of trails through forests and meadows. Great for family nature walks and bird watching.",
      category: "TRAIL" as const,
      latitude: 35.2547, longitude: -80.7739,
      address: "2900 Rocky River Rd, Charlotte, NC 28215",
      city: "Charlotte", state: "NC", zipCode: "28215",
      cost: "FREE" as const, isIndoor: false, isOutdoor: true,
      ageMin: 3, ageMax: 99,
      seasonality: ["spring", "summer", "fall"],
      tags: ["nature", "trails", "birds", "forest", "family hiking"],
      rating: 4.5, reviewCount: 1800,
    },
    {
      id: "act-clt-camp-north-end",
      title: "Camp North End",
      description: "Mixed-use creative campus with food hall, art installations, breweries, and regular family-friendly community events.",
      category: "ENTERTAINMENT" as const,
      latitude: 35.2431, longitude: -80.8566,
      address: "300 Camp Rd, Charlotte, NC 28206",
      city: "Charlotte", state: "NC", zipCode: "28206",
      cost: "FREE" as const, isIndoor: true, isOutdoor: true,
      ageMin: 0, ageMax: 99,
      seasonality: ["spring", "summer", "fall", "winter"],
      tags: ["food hall", "art", "community", "events", "creative"],
      rating: 4.4, reviewCount: 3200,
    },
  ];

  for (const activity of activities) {
    await prisma.activity.upsert({
      where: { id: activity.id },
      update: { ...activity },
      create: { ...activity },
    });
  }
  console.log(`  Seeded ${activities.length} activities across 5 cities`);
}

async function seedRecommendations() {
  console.log("Seeding activity recommendations...");

  const recommendations = [
    {
      id: "rec-family-game-night",
      title: "Family Game Night",
      description: "Set aside one evening a week for board games, card games, or video games together. Great for bonding and creating traditions.",
      category: "at-home",
      cost: "Budget ($20-50 for games)",
      duration: "2-3 hours",
      ageRange: "4+",
      isIndoor: true, isOutdoor: false,
      tags: ["games", "bonding", "weekly", "tradition", "indoor"],
    },
    {
      id: "rec-nature-scavenger-hunt",
      title: "Nature Scavenger Hunt",
      description: "Create a list of items to find on a nature walk — pinecones, specific birds, different leaf shapes. Educational and adventurous!",
      category: "outdoor",
      cost: "Free",
      duration: "1-2 hours",
      ageRange: "3-12",
      isIndoor: false, isOutdoor: true,
      tags: ["nature", "scavenger hunt", "educational", "hiking", "kids"],
    },
    {
      id: "rec-cooking-together",
      title: "Family Cooking Challenge",
      description: "Pick a recipe together and cook as a family. Take turns choosing cuisines from around the world each week.",
      category: "at-home",
      cost: "Budget ($15-30 for ingredients)",
      duration: "1-2 hours",
      ageRange: "5+",
      isIndoor: true, isOutdoor: false,
      tags: ["cooking", "bonding", "educational", "food", "culture"],
    },
    {
      id: "rec-bike-ride-adventure",
      title: "Family Bike Ride",
      description: "Explore local bike trails together. Pack snacks and water, pick a scenic route, and enjoy the ride at everyone's pace.",
      category: "outdoor",
      cost: "Free (if you have bikes)",
      duration: "1-3 hours",
      ageRange: "5+",
      isIndoor: false, isOutdoor: true,
      tags: ["biking", "exercise", "outdoor", "adventure", "trails"],
    },
    {
      id: "rec-movie-marathon",
      title: "Themed Movie Marathon",
      description: "Pick a theme (superhero, animated classics, space) and watch 2-3 movies with themed snacks. Build a blanket fort for bonus points!",
      category: "at-home",
      cost: "Budget ($10-20 for snacks)",
      duration: "4-6 hours",
      ageRange: "3+",
      isIndoor: true, isOutdoor: false,
      tags: ["movies", "cozy", "snacks", "blanket fort", "themed"],
    },
    {
      id: "rec-volunteer-together",
      title: "Family Volunteer Day",
      description: "Volunteer together at a local food bank, animal shelter, or community garden. Teaches kids empathy while making a difference.",
      category: "community",
      cost: "Free",
      duration: "2-4 hours",
      ageRange: "6+",
      isIndoor: true, isOutdoor: true,
      tags: ["volunteer", "community", "charity", "teaching", "empathy"],
    },
  ];

  for (const rec of recommendations) {
    await prisma.activityRecommendation.upsert({
      where: { id: rec.id },
      update: rec,
      create: rec,
    });
  }
  console.log(`  Seeded ${recommendations.length} activity recommendations`);
}

async function main() {
  console.log("Starting FamilySync database seed...\n");

  await seedCharities();
  await seedActivities();
  await seedRecommendations();

  console.log("\nSeed completed successfully!");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
